# syntax=docker/dockerfile:1.7
FROM --platform=$BUILDPLATFORM alpine:latest AS source

ARG UPSTREAM_REPO="https://github.com/WhatsApp/proxy.git"
ARG UPSTREAM_REF="main"

RUN apk add --no-cache git ca-certificates \
 && set -eux; \
    test -n "${UPSTREAM_REF}"; \
    git init /src/repo; \
    cd /src/repo; \
    git remote add origin "${UPSTREAM_REPO}"; \
    git fetch --depth 1 origin "${UPSTREAM_REF}"; \
    git checkout --detach FETCH_HEAD; \
    sed -i '/^chown haproxy:haproxy /d' proxy/src/start.sh; \
    mkdir -p /runtime-dirs/certs /runtime-dirs/etc-haproxy-ssl /runtime-dirs/home-haproxy-certs

FROM --platform=linux/amd64 haproxy:lts-alpine AS linux-amd64
RUN apk --no-cache add curl openssl jq bash

FROM --platform=linux/arm64 haproxy:lts-alpine AS linux-arm64
RUN apk --no-cache add curl openssl jq bash

FROM --platform=linux/arm/v7 haproxy:lts-alpine AS linux-armv7
RUN apk --no-cache add curl openssl jq bash

# Generated by Dockerfile.rootfs-armv5. This is intentionally a local archive:
# neither Alpine nor the official HAProxy image publishes linux/arm/v5.
FROM --platform=linux/arm/v5 scratch AS linux-armv5
ADD rootfs.tar /

FROM ${TARGETOS}-${TARGETARCH}${TARGETVARIANT}

USER root

COPY --from=source --chmod=755 /src/repo/proxy/src/generate-certs.sh /usr/local/bin/generate-certs.sh
COPY --from=source --chmod=755 /src/repo/proxy/src/start.sh /usr/local/bin/start.sh
COPY --from=source --chmod=755 /src/repo/proxy/src/healthcheck.sh /usr/local/bin/healthcheck.sh
COPY --from=source /src/repo/proxy/src/proxy_config.cfg /usr/local/etc/haproxy/haproxy.cfg
COPY --from=source /runtime-dirs/certs/ /certs/
COPY --from=source /runtime-dirs/etc-haproxy-ssl/ /etc/haproxy/ssl/
COPY --from=source /runtime-dirs/home-haproxy-certs/ /home/haproxy/certs/

HEALTHCHECK --interval=10s --start-period=5s CMD bash /usr/local/bin/healthcheck.sh
CMD ["/usr/local/bin/start.sh"]
